export enum ActionTypeEnum{

    DELETE = 'DELETE',
    BLOCK = 'BLOCK',
    UNBLOCK = 'UNBLOCK',
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED',
    DISMISS = 'DISMISS',
    PAYOUT = 'PAYOUT',
    PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
}